image: golang:1.19

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"



format:
  script:
    - test -z "$(gofmt -l ./)"

vet:
  script:
    - go vet -json ./... | tee go-vet-report.json
  artifacts:
    when: always
    paths:
      - go-vet-report.json
    expire_in: 1 hour


staticcheck:
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@2022.1
    - staticcheck ./...

test:
  script:
    - go test -v -coverprofile=go-coverage.out -json ./... | tee go-test-report.json
  artifacts:
    when: always
    paths:
      - go-test-report.json
      - go-coverage.out
    expire_in: 1 hour

golint:
  script:
    - go install golang.org/x/lint/golint@v0.0.0-20210508222113-6edffad5e616
    - golint -set_exit_status ./...

build:
  script:
    - go build ./...
  artifacts:
    # instead of manually adding i.e. the built binaries, we can instead just
    # grab anything not tracked in Git
    untracked: true
    expire_in: 1 hour
