# CI : test, build, lint

name: Code quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: build
      run: go build ./...

    - name: test
      run: go test -v -coverprofile=go-coverage.out -json ./... | tee go-test-report.json

    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: code-test-report
        path: go-test-report.json
        retention-days: 1

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: go-coverage.out
        retention-days: 1

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run server
        run: go run main.go serve &
      - name: test server
        run: go run main.go test ./stdcov-cli --verbose --server "http://localhost:1323" --url /driver_journeys -q departureLat=0 -q departureLng=0 -q arrivalLat=0 -q arrivalLng=0 -q departureDate=1665500000 -q timeDelta=2000000000 -q departureRadius=500000 -q arrivalRadius=50000

